import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative h-32 sm:h-48 bg-cover bg-center" style={{ backgroundImage: "url('/banner.png')" }}>
          <div className="absolute inset-0 bg-black opacity-50"></div>
          <div className="relative z-10 flex items-center justify-center h-full text-center px-4">
            <h1 className="text-white text-2xl sm:text-4xl font-bold">BIG SLEEK SALES CONFERENCE: 2025</h1>
          </div>
        </div>
        <div className="min-h-screen bg-gray-50 lg:grid lg:grid-cols-12">
          <div className="lg:col-span-2">
            <NavBar />
          </div>
          <div className="lg:col-span-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}